= Настройка использования МЧД

Система {dv} обеспечивает создание и хранение машиночитаемых доверенностей (МЧД). Система генерирует МЧД в формате ФНС.

МЧД -- это электронный документ в формате XML, подписанный электронной подписью доверителя или его уполномоченного представителя (в случае доверенности, выданной в порядке передоверия).

.МЧД содержит следующие данные:
* Доверитель -- организация, индивидуальный предприниматель или физическое лицо, выдавшее доверенность.
* Физическое лицо, подписавшее доверенность от имени доверителя.
* Доверенное лицо -- организация, индивидуальный предприниматель или физическое лицо, которое уполномочено совершать действие от имени доверителя.
* Описание полномочий.

.Для работы с МЧД в системе {dv} предусматривается:
. API подсистемы МЧД модуля {bo}, предоставляющий следующие возможности:
+
* Создание системной карточки доверенности.
* Генерация XML-файла МЧД указанных выше форматов.
* Формирование ЭП к XML-файлу МЧД.
* Проверка МЧД.
* Изменение статуса МЧД.
* Экспорт МЧД.
* Отзыв МЧД.
+
. Системная карточка доверенности (СКД) с подписью и без UI.
+
Карточка имеет три статуса: `Подготовка` (Preparation), `Действует` (Valid), `Отозвана` (Revoked). Подробное описание СКД приведено в руководстве разработчика, в разделе "xref:programmer:cards:.attorney.adoc[]".
+
. API для работы с системной карточкой, в том числе подходящий для {wincl}а. API позволяет создавать карточку несколькими путями. См. подробнее в руководстве разработчика, в разделе "xref:.BackOffice-ObjectModel-Powers:PowerOfAttorney_CL.adoc[PowerOfAttorney -- класс]".
. Генерация XML доверенности стандартного формата, см. подробнее в разделе "xref:5.5.17@webclient:programmer:other/.powers-of-attorney.adoc[]".
. Формирование ЭП для XML.
. Заполнение атрибутов:
+
* Доверитель.
* Представитель.
* Полномочия.
* Функции получения атрибутов из связанной карточки СКД.
+
. Формирование ЭП в {wc}е и в {wincl}е и использование карточки МЧД в стандартных диалогах подписания, см. подробнее "xref:5.5.17@webclient:user:docs-sign.adoc#attorney[Подписание с использованием МЧД]".
. Проверка действительности доверенности в момент подписания, включая отозванность.
. Проверка МЧД при проверке ЭП в {wc}е и в {wincl}е с использованием МЧД.
. Отображение информации о доверенности в журнале электронных подписей.
. Визуализация штампа ЭП, включая штамп с доверенностью.
. Загрузка сторонних доверенностей.
. xref:5.5.17@webclient:user:directories/powers/.directory.adoc[Справочник кодов полномочий].
. Пользовательская карточка доверенности (ПКД) -- карточка создаётся администратором системы. Подробнее можно ознакомиться с примером в документации разработчика web-решений, в разделе "xref:5.5.17@webclient:programmer:other/.powers-of-attorney.adoc[]".

[#formats]
== Форматы доверенности

Система хранит различные форматы МЧД:

* Формат единой формы доверенности в электронной форме в машиночитаемом виде (МЧД) (формат `ON_DOVBB_1_928_00_01_02`).
* Формат доверенности, подтверждающей полномочия представителя налогоплательщика (плательщика сбора, плательщика страховых взносов, налогового агента) в отношениях, регулируемых законодательством о налогах и сборах, в электронной форме (формат `ON_DOVEL_1_885_00_05_01`).
* Система позволяет хранить собственные разрабатываемые форматы.

Стандартные форматы указаны в _Справочнике полномочий_.

Два указанных выше стандартных формата доверенностей будут загружены в Справочник полномочий при загрузке модуля _{bo}_ с помощью Консоли настройки {dv}.

Загрузка стандартных настроек модуля _{bo}_ может быть пропущена. В таком случае потребуется самостоятельно импортировать файл `C:\Program Files (x86)\Docsvision\BackOffice\CardPackage\RefPowers.xml`.

[#settings]
== Настройка МЧД

Чтобы при подписании запускался алгоритм подбора МЧД необходимо выполнить настройки:

. В справочнике типов карточек для карточек типа _Документ_ перейдите на вкладку _Подпись_.
. В поле _Использовать машиночитаемую доверенность при подписании_ выберите значение из списка:
+
--
* *_Не требуется_* -- значение по умолчанию
* *_Желательно_*
* *_Обязательно_*
--
+
При подписании документа выполняется проверка необходимости МЧД для вида документа. В зависимости от выбранного значения в поле _Использовать машиночитаемую доверенность при подписании_, алгоритм подбора МЧД выполняет или пропускает поиск доверенностей.
+
* Если значение поля *_Обязательно_* или *_Желательно_*, сразу начинается _Проверка необходимости МЧД для подписанта_.
* Если значение поля *_Не требуется_*, то процесс подбора завершается, МЧД не требуется, дальнейшие операции не выполняются.
+
См. подробнее "xref:5.5.5@backoffice:desdirs:card-kinds/document/sign-card.adoc#attorney[Использовать МЧД при подписании]" в разделе с описанием конструкторов и справочников.
+
. В карточку сотрудника, на вкладку _Основная_ добавлен флаг `*Требуется доверенность при подписании документов*`. Флаг влияет на алгоритм выбора МЧД при подписании документа и учитывается при проверке необходимости использования МЧД для сотрудника.
+
* Если флаг установлен, выполняется переход к следующим этапам.
* Если флаг не установлен, процесс подбора завершается, МЧД не требуется, дальнейшие операции не выполняются.
+
См. подробнее в документации справочника сотрудников в документации модуля xref:5.5.5@backoffice:desdirs:staff/employees/main-tab.adoc#attorney[_{bo}_] и модуля xref:5.5.17@webclient:user:directories/staff/employee-fields.adoc#attorney[_{wc}_].

Работа с СКД (создание, передоверие, отправка в реестр и прочее) выполняется через API, см. подробнее в документации разработчика. раздел "xref:programmer:cards:.attorney.adoc[]" и документации разработчика web-решений, раздел "xref:5.5.17@webclient:programmer:other/.powers-of-attorney.adoc[]".

[#algorithm]
== Алгоритм выбора МЧД

За алгоритм выбора МЧД отвечает специальный сервис, который определят необходимость МЧД для пользователя (подписанта документа) и подбирает МЧД в случае необходимости.

Сервис имеет возможность программного расширения, кодом можно задать дополнительную фильтрацию отобранных МЧД.

Входными данными для сервиса являются пользователь (подписант документа) и ссылка на карточку документа.

Стартовым событием работы сервиса является фокус на сертификате в окне выбора. Для простой подписи подбор МЧД не выполняется.

. Сначала проверяется необходимость МЧД для вида документа и подписанта:
+
Выполняется проверка необходимости МЧД для вида документа. +
Проверяется значение поля _Использовать машиночитаемую доверенность при подписании_ в xref:5.5.5@backoffice:desdirs:card-kinds/document/sign-card.adoc#attorney[справочнике видов] у вида документа.
+
* Если значение поля *_Обязательно_* или *_Желательно_*, сразу начинается _Проверка необходимости МЧД для подписанта_.
* Если значение поля *_Не требуется_*, то процесс подбора завершается, МЧД не требуется, дальнейшие операции не выполняются.
+
. _Проверка необходимости МЧД для подписанта_.
+
Выполняется проверка флага `*Требуется доверенность при подписании документов*` в xref:5.5.17@webclient:user:directories/staff/employee-fields.adoc#attorney[карточке сотрудника-подписанта] в справочнике сотрудников.
+
* Если флаг установлен, выполняется переход к следующим этапам.
* Если флаг не установлен, процесс подбора завершается, МЧД не требуется, дальнейшие операции не выполняются.

Если МЧД требуется для вида документа (*_Обязательна_* или *_Желательна_*) и подписанта, выполняется подбор МЧД среди тех, которые выданы подписанту и находятся в базе данных системы.

Сервис проверяет каждую из имеющихся доверенностей. Состав проверки состоит из следующих операций.

[start=3]
. Подбор МЧД для подписанта
+
По полю "представитель" системной карточки доверенности подбираются МЧД из базы данных, которые выданы на подписанта. Далее выполняется проверка статусов МЧД.
+
. Проверка статуса МЧД
+
Выполняется запрос в базу данных с проверкой статуса СКД.
+
* Если статус СКД `Действует`, данная операция завершена успешна, выполняется следующая операция.
* Если статус СКД `Отозвана`, доверенность не подходит.
+
. Проверка срока действия МЧД.
+
Проверяется срок действия МЧД (срок действия СКД). Срок действия МЧД сравнивается с сегодняшним днём.
+
* Если срок действия МЧД больше или равен "сегодня", доверенность подходит и попадает в список доступных доверенностей.
* Если срок действия МЧД меньше "сегодня", доверенность не подходит.

В результате выполнения алгоритма формируется список подходящих для пользователя МЧД. Список сортируется сначала по доверителю, затем по дате совершения доверенности. Сортировка выполняется по возрастанию.

Если сервис не подобрал ни одной МЧД в ситуации, где она обязательна или желательна, будет выдано сообщение об отсутствии подходящей МЧД. В такой ситуации пользователь не сможет подписать документ квалифицированной электронной подписью.
