= Настройка разметок

Разметка -- шаблон, по которому формируется пользовательский интерфейс карточки или другого элемента пользовательского интерфейса.

В системе {dv} есть два типа разметок: разметки {wc}а и разметки {wincl}а.

Для {wc}а могут быть разработаны разметки для всех основных элементов пользовательского интерфейса: главной страницы, дерева папок, карточек, различных форм. Настройка разметок выполняется с помощью программы _{kvr}_, являющейся частью модуля _{dv} 5. {wc}_.

Для {wincl}а предоставляется возможность настраивать разметки карточек. Некоторые другие элементы интерфейса могут быть настроены встроенные средствами {wincl}а. Настройка разметок выполняется с помощью _Конструктора разметок_, являющегося карточкой модуля _{dv} 5. Базовые объекты_.

.Инструкция по настройке разметок приведена в документации модулей:
* Для модуля {wincl}: раздел xref:baseobjects:desdirs:LayoutDesigner.adoc[Конструктор разметок].
* Для модуля {wc}: документ xref:webclient:layouts:infoInstall.adoc[Руководство пользователя программы {kvr}].
