= Настройка использования МЧД

Система {dv} обеспечивает создание и хранение машиночитаемых доверенностей (МЧД). Система генерирует МЧД в формате ФНС.

МЧД -- это электронный документ в формате XML, подписанный электронной подписью руководителя организации. Документ содержит данные о доверителе -- организации, выдавшей доверенность, доверенном лице -- физическом лице, которое уполномочено совершать действие и полномочиях.

.Для работы с МЧД в системе {dv} предусматривается:
. Системная карточка доверенности (СКД) с подписью и без UI. +
Карточка имеет три статуса: `Проект`, `Действует`, `Отозвана`.
+
.СКД предоставляет следующие возможности:
* Генерация XML-файла МЧД стандартного формата.
* Формирование ЭП к XML-файлу МЧД.
* Проверка МЧД.
* Изменение статуса МЧД.
+
См. описание СКД подробнее в руководстве разработчика, в разделе "xref:programmer:cards:attorney.adoc[]".
+
. API для работы с системной карточкой, в том числе подходящий для {wincl}а. API позволяет создавать карточку несколькими путями. См. подробнее в руководстве разработчика, в разделе "xref:programmer:BackOffice-ObjectModel-Powers:PowerOfAttorney_CL.adoc[PowerOfAttorney]".
. Генерация XML доверенности стандартного формата, см. подробнее в разделе "xref:webclient:programmer:other/powers-of-attorney.adoc[]".
. Формирование ЭП для XML.
. Заполнение атрибутов:
+
* Доверитель.
* Представитель.
* Полномочия.
* Функции получения атрибутов из связанной карточки СКД.
+
. Формирование ЭП в {wc}е и в {wincl}е и использование карточки МЧД в стандартных диалогах подписания, см. подробнее "xref:webclient:user:docs-sign.adoc#attorney[Подписание с использованием МЧД]".
. Проверка действительности доверенности в момент подписания, включая отозванность.
. Проверка ЭП в {wc}е и в {wincl}е с использованием МЧД.
. Отображение информации о доверенности в журнале электронных подписей.
. Визуализация штампа ЭП, включая штамп с доверенностью.
. Загрузка новых доверенностей.
. xref:webclient:user:directories/attorney/directory.adoc[Справочник кодов полномочий].
. Пользовательская карточка доверенности (ПКД) -- карточка создаётся администратором системы.

[#formats]
== Форматы доверенности

Система хранит различные форматы МЧД:

* Формат единой формы МЧД.
* Формат МЧД, подтверждающей полномочия представителя налогоплательщика.
* Собственные разрабатываемые форматы.

Стандартные форматы указаны в _Справочнике полномочий_.

Два указанных выше стандартных формата доверенностей будут загружены в Справочник полномочий при загрузке модуля _{bo}_ с помощью Консоли настройки {dv}.

Загрузка стандартных настроек модуля _{bo}_ может быть пропущена. В таком случае потребуется самостоятельно импортировать файл `C:\Program Files (x86)\Docsvision\BackOffice\5.5\CardPackage\RefPowers.xml`.

[#settigns]
== Настройка МЧД

Расписать про справочники, и прочее. Дать ссылки на вин и веб

Работа с скд через AP, дать ссылки на программиста xref:programmer:cards:attorney.adoc[]

[#algorithm]
== Алгоритм выбора МЧД

За алгоритм выбора МЧД отвечает специальный сервис, который определят необходимость МЧД для пользователя (подписанта) и подбирает МЧД в случае необходимости.

Сервис имеет возможность программного расширения, кодом можно задать дополнительную фильтрацию отобранных МЧД.

Входными данными для сервиса являются пользователь (подписант) и ссылка на карточку документа.

Стартовым событием работы сервиса является фокус на сертификате в окне выбора. Для простой подписи подбор МЧД не выполняется.

. Сначала проверяется необходимость МЧД для вида документа и подписанта:
+
Выполняется проверка необходимости МЧД для вида документа. +
Проверяется значение поля _Использовать машиночитаемую доверенность при подписании_ в xref:backoffice:desdirs:card-kinds/document/sign-card.adoc#attorney[справочнике видов] у вида документа.
+
* Если значение поля *_Обязательно_* или *_Желательно_*, сразу начинается _Проверка необходимости МЧД для подписанта_.
* Если значение поля *_Не требуется_*, то процесс подбора завершается, МЧД не требуется, дальнейшие операции не выполняются.
+
. _Проверка необходимости МЧД для подписанта_.
+
Выполняется проверка флага `*Требуется доверенность при подписании документов*` в xref:webclient:user:directories/staff/employee-fields.adoc#attorney[карточке сотрудника-подписанта] в справочнике сотрудников.
+
* Если флаг установлен, выполняется переход к следующим этапам.
* Если флаг не установлен, процесс подбора завершается, МЧД не требуется, дальнейшие операции не выполняются.

Если МЧД требуется для вида документа (*_Обязательна_* или *_Желательна_*) и подписанта, выполняется подбор МЧД среди тех, которые выданы подписанту и находятся в базе данных системы.

Сервис проверяет каждую из имеющихся доверенностей. Состав проверки состоит из следующих операций.

[start=3]
. Подбор МЧД для подписанта
+
По полю "представитель" системной карточки доверенности подбираются МЧД из базы данных, которые выданы на подписанта. Далее выполняется проверка статусов МЧД.
+
. Проверка статуса МЧД
+
Выполняется запрос в базу данных с проверкой статуса СКД.
+
* Если статус СКД `Действует`, данная операция завершена успешна, выполняется следующая операция.
* Если статус СКД `Отозвана`, доверенность не подходит.
+
. Проверка срока действия МЧД.
+
Проверяется срок действия МЧД (срок действия СКД). Срок действия МЧД сравнивается с сегодняшним днём.
+
* Если срок действия МЧД больше или равен "сегодня", доверенность подходит и попадает в список доступных доверенностей.
* Если срок действия МЧД меньше "сегодня", доверенность не подходит.

В результате выполнения алгоритма формируется список подходящих для пользователя МЧД. Список сортируется сначала по доверителю, затем по дате совершения доверенности. Сортировка выполняется по возрастанию.

Если сервис не подобрал ни одной МЧД в ситуации, где она обязательна или желательна, будет выдано сообщение об отсутствии подходящей МЧД.
