= Настройка разметок

Разметка – шаблон, по которому формируется пользовательский интерфейс карточки или другого элемента пользовательского интерфейса.

В системе Docsvision есть два типа разметок: разметки Web-клиента и разметки Windows-клиента.

Для Web-клиента могут быть разработаны разметки для всех основных элементов пользовательского интерфейса: главной страницы, дерева папок, карточек, различных форм. Настройка разметок выполняется с помощью программы «Конструктор web-разметок», являющейся частью модуля «Docsvision 5. Web-клиента».

Для Windows-клиента предоставляется возможность настраивать разметки карточек. Некоторые другие элементы интерфейса могут быть настроены встроенные средствами Windows-клиента. Настройка разметок выполняется с помощью «Конструктора разметок», являющегося карточкой модуля «Docsvision 5. Базовые объекты».

Инструкция по настройке разметок приведена в документации модулей:

* для модуля «Windows-клиент»: документ «Описание конструкторов и справочников», модуль «Docsvision 5. Базовые объекты», пункт «Конструктор разметок»;
* для модуля «Web-клиент»: документ «Руководство пользователя программы Конструктор web-разметок», модуль «Docsvision 5. Web-клиента».
