= Признак изменения запроса на уровне БД

При необходимости ручной оптимизации хранимых процедур существует возможность включить признак изменения запроса на уровне БД (признак отключения регенерации). В случае, если этот признак установлен, поисковый запрос никогда не регенерируется (в т.ч. при обновлении БД).

Флаг для включения признака *Изменение на уровне БД* доступен в следующих диалогах:

. xref:Search_Loading_and_Change_Query.adoc[Диалог загрузки] поискового запроса. Запросы с установленным признаком отображаются серым шрифтом. Такие запросы можно выбрать или открыть, при изменении и попытке сохранить запрос, будет предложено сохранить запрос как новый. При позиционировании на таком запросе, активный флаг *Изменение на уровне БД* доступен для снятия.
+
При снятии флага запрос выделяется черным шрифтом. В данном случае хранимая процедура не удаляется, удаляется только признак отключения перегенерации (флаг).
. xref:Search_Loading_and_Change_Query.adoc[Диалог редактирования] поискового запроса. Если для запроса флаг *Изменение на уровне БД* активен, запрос можно выбрать и открыть, но нельзя изменить.
+
Хранимая процедура, измененная в БД, может быть перезаписана только при сохранении запроса, если признак был отключен на этапе загрузки запроса.
. Диалог сохранения поискового запроса (*Сохранить как...)*. Для обычных запросов флаг *Изменение на уровне БД* действует по аналогии с диалогом из первого пункта — запросы с активным флагом выделяются серым шрифтом, флаг доступен для снятия. Такие запросы нельзя выбрать для сохранения.

[NOTE]
====
Флаг *Изменение на уровне БД* недоступен для параметрических запросов.
====
