= Сервис обслуживания ЭП

Сервис обслуживания ЭП -- компонент модуля {bo}. Сервис указывает в журнале подписей {wc}а актуальный статус подписи, тип и дату окончания срока действия сертификата. Сервис обслуживания ЭП может работать в сочетании с Криптосервисом -- Docker-контейнером, выполняющим функции обслуживания ЭП.

[#functions]
== Функциональные возможности сервиса обслуживания ЭП

WARNING: Сервис обслуживания ЭП -- расширение, входящее в стандартную поставку модуля {bo}, не следует путать его с Криптосервисом. Криптосервис поставляется в виде Docker-контейнера.

.Сервис обслуживания подписи:
* Если срок действия сертификата не истёк, Сервис указывает в карточке актуальный статус подписи, тип и дату окончания срока действия сертификата, даёт возможность просматривать дополнительную информацию о подписи в xref:6.1@webclient:user:docs-sign.adoc#advanced-info[журнале подписей {wc}а].

.Криптосервис дополняет функции сервиса по обслуживанию следующими возможностями:
* Если срок действия сертификата не истёк, Криптосервис доступен и функционирует, в карточку добавляется новый архивный штамп времени и улучшает подпись до CAdES-A.
* В {dv} версии 6.1 и выше Криптосервис является обязательным для проверки подписей CAdES-BES и CAdES-X Long Type 1 с нестандартными для .NET 6 алгоритмами в сертификатах. Требуется, например, при использовании сертификатов КриптоПро.

Из-за использования библиотеки tspcom.dll Криптосервис требует быть развернут минимум в 32-битном процессе Службы рабочих процессов.

[#cryptoservice]
== Установка и запуск Криптосервиса

.Криптосервис работает с {dv} следующих версий:
* Модуль "{pl}" версии 6.1 и выше + "{wc}" 18 и выше. +
Криптосервис является обязательным для проверки подписей с нестандартными для .NET 6 алгоритмами в сертификатах. Требуется, например, при использовании сертификатов КриптоПро.
* Модуль "{pl}" версии 5.5.5 + "{wc}" 17. +
Криптосервис указывает в xref:webclient:user:docs-sign.adoc#advanced-info[журнале подписей {wc}а] актуальный статус подписи, тип и дату окончания срока действия сертификата, делает доступной расширенную информацию о подписи.
* Модуль "{pl}" версии 5.5.4 + "{wc}" 16 + "Служба рабочих процессов" версии 5.5.1. +
Функциональность аналогична предыдущему пункту.

Криптосервис поставляется в виде Docker-контейнера, для его использования требуется https://www.docker.com/[Docker] актуальной версии и опция лицензии {dv} _Сервис обслуживания электронной подписи_ (только для добавления архивного штампа времени).

Криптосервис можно установить и запустить командой:

[source,bash]
----
docker run -d -p 8100:8094 packages.docsvision.com/docsvision/cryptoservice
----

Настройки криптосервиса задаются в командной строке.

При запуске контейнера необходимо связать порт хоста с портом контейнера, например, `-p 8100:8094`. В примере `8100` -- порт хоста, `8094` -- порт контейнера. Для работы функций проверки и формирования подписи сервер {dv} должен подключаться к контейнеру через порт хоста. Адрес Криптосервиса указывается в конфигурационном файле модуля {pl}, <<config,см. подробности ниже>>.

По умолчанию Криптосервис использует TSP-службу с адресом `http://cryptopro.ru/tsp/tsp.srf`. При необходимости адрес используемой TSP-службы можно переопределить с помощью переменной окружения `TSP_SERVICE_ADDRESS`. Ниже приведён пример переопределения адреса TSP-сервиса:

[source,bash]
----
docker run -d -p 8100:8094 -e TSP_SERVICE_ADDRESS=http://testca2012.cryptopro.ru/tsp/tsp.srf packages.docsvision.com/docsvision/cryptoservice
----

Контейнер поставляется в комплекте со следующими сертификатами:

* https://www.gosuslugi.ru/crt[Защищённые сертификаты Минцифры].
* https://ca.kontur.ru/about/certificates[Сертификаты УЦ "Контур"].
* https://tlsca.cryptopro.ru/UI/CaCerts.aspx[Сертификаты "Крипто-Про УЦ 2.0" (TLS CA)].
* http://cpca20.cryptopro.ru/[Сертификаты УЦ ООО "Крипто-Про"].

При необходимости использования дополнительных сертификатов выполните одну из следующих настроек:

* Укажите путь к папке сертификатов:
. Необходимые сертификаты сохраните в отдельную папку на диске Docker-хоста.
. Смонтируйте в каталог `/var/cryptoservice/cacerts` Docker-контейнера и запустите контейнер. +
При запуске контейнера всё содержимое папки будет импортировано в хранилище.
+
[source,bash]
----
docker run -d -p 8100:8094 -v D:\Cert:/var/cryptoservice/cacerts packages.docsvision.com/docsvision/cryptoservice
----
+
* Заново соберите образ:
+
. Создайте Dockerfile:
+
[source,dockerfile]
----
FROM packages.docsvision.com/docsvision/cryptoservice
COPY ./your/cacerts/ /var/cryptoservice/cacerts/
----
+
. Соберите собственный образ:
+
[source,bash]
----
docker build . -t cryptoservice
----
+
. Запустите контейнер:
+
[source,bash]
----
docker run -d -p 8100:8094 cryptoservice
----

[#config]
После установки Криптосервиса укажите его в параметре `ComplexSignatureServiceAddress` конфигурационного файла модуля {pl} по пути `/usr/lib/docsvision/platform/appsettings.json`:

[source,json]
----
  "DocsVision": {
    "BackOffice": {
      "Server": {
        "Extension": {
          "ComplexSignatureServiceAddress": "ConnectAddress=http://server.domain.com:8100/cryptoservice/api/v1" <.>
        }
      }
    }
  }
----
<.> Адрес Криптосервиса.

[#registry]
== Настройки Криптосервиса в реестре

include::partial$excerpts.adoc[tags=java-warning]

.Чтобы изменить настройки, перейдите в ветку реестра:
. `{hklm-dv}\WorkerService\Connections\DocsVision`.
. В указанной ветке реестра создайте параметр для подключения к БД с произвольным именем. Это может быть, например, параметр с именем БД. В значении параметра укажите строку подключения к используемой в {dv} БД следующего вида:
+
 ConnectAddress=http://servername/StorageServer/StorageServerService.asmx;BaseName=basename
+
--
* Вместо `servername` укажите адрес подключения к серверу {dv}.
* Вместо `basename` укажите название БД.
--
+
NOTE: Один экземпляр рабочего процесса Криптосервиса может обрабатывать только одну БД. Соответственно, для каждого экземпляра сервиса нужно добавлять новый параметр для подключения к БД.

[#handling]
== Настройка обработки подписей

include::partial$excerpts.adoc[tags=java-warning]

Обработка подписей Сервисом зависит от настроек, записанных в ветке:

`{hklm-dv}\SOFTWARE\DocsVision\WorkerService\Components\Signatures`

.Сервис обрабатывает подписи в следующих случаях:
* Если срок действия сертификата подписи не больше заданного в значении `DaysOffset`.
* Если не превышено заданное количество карточек с подписями в значении `BatchSize`.
* Если наступил интервал, заданный в значении `Schedule`.

.Чтобы задать собственные настройки для обработки подписей:
. В указанной ветке реестра найдите параметр `SignaturesPeriodComponentSetting` и измените в его значении:
+
* Значение `DaysOffset`. Указывает, за сколько дней до наступления даты окончания срока действия сертификата Сервис будет обрабатывать подписи.
+
Если значение не задано, используется значение по умолчанию -- `180 дней`.
+
* Значение `Schedule`. Указывает на периодичность обработки подписей Сервисом. В строке, объединенной через `;`, можно задавать список времени срабатывания.
+
Если значение не задано, используется значение по умолчанию -- `60 секунд`.
+
* Значение `BatchSize`. Количество карточек, которое Сервис ищет и обрабатывает за один раз.
+
Если значение не задано, используется значение по умолчанию -- `500 карточек`.

События работы сервиса записываются в журнал Службы рабочих процессов, расположенный по адресу: `C:\ProgramData\Docsvision\WorkerService\Logs`.
