= Локализация

В системе Docsvision реализовано несколько уровней поддержки локализации данных:

* на уровне метаданных (схем карточек): локализация названий библиотек карточек, карточек, секций и полей, перечисляемых значений и т. п.
* на уровне представления данных:
** локализация разметок,
** локализация представлений,
** локализация названий папок.

Настройка локализации метаданных рассмотрена в руководстве пользователя «Комплекта программных инструментов «Resource Kit», пункт «Docsvision 5 CardManager».

Локализация разметок выполняется с помощью:

* Конструктора разметок – для Windows-клиента. Обратитесь к документу «Docsvision 5. Базовые объекты. Описание конструкторов и справочников», пункт «Локализация разметки».
* Конструктора web-разметок – для Web-клиента. Обратитесь к руководству пользователя программы «Конструктор web-разметок», пункт «Локализация свойств элемента управления».

Локализация представлений и поисковых запросов рассмотрена в настоящем документе в пунктах: xref:ViewLocalization.adoc[Локализация представлений] и xref:SearchLocalization.adoc[Локализация поисковых запросов].

Информация по использованию локализованных названий папок приведена в руководстве пользователя модуля «Docsvision 5. Windows-клиент».
