= Особенности наследования мандатной безопасности

Объект может унаследовать уровень доступа только от родительского объекта (папки или карточки) Docsvision, субъект Docsvision (владелец объекта) передать объекту свой уровень допуска не может.

Чтобы распространить уровень доступа на *все существующие в данный момент* дочерние объекты, необходимо использовать функцию «Применить к дочерним объектам» при настройке мандатной безопасности родительского объекта. Операция наследования уровня доступа является *атомарной*: новые дочерние объекты этого же родительского объекта будут создаваться с самым низким уровнем доступа.

[NOTE]
====
[.note__title]#Important:# Новый уровень доступа унаследуют и те дочерние объекты, у которых ранее он был выше, чем у родительского.
====

Уровень доступа наследуется только по сильной ссылке. Например, если был изменен уровень доступа папки и при этом был установлен флаг [.ph .uicontrol]*Применить к дочерним объектам*, то:

* будет изменен уровень доступа всех вложенных папок;
* будет изменен уровень доступа всех карточек, находящихся в папке и вложенных папках;
* будет изменен уровень доступа всех файлов и карточек файлов, приложенных к этим карточкам;
* будет изменен уровень доступа карточек задач и согласований, созданных из этих карточек;
* не будет изменен уровень доступа карточек, на которые ссылаются эти карточки;
* не будет изменен уровень доступа карточек, созданных из этих карточек (связанных с ними темой обработки).

*Parent topic:* xref:../topics/MandateConfig.adoc[Настройка мандатной безопасности]
