= Ввод сервера {dv} в домен Samba

В качестве альтернативы Microsoft Active Directory можно использовать Samba. Запуск Samba поддерживается в нескольких разных средах, описание всех возможных способов запуска выходит за рамки данной документации.

Установка и запуск Samba сводится к нескольким командам, за подробной информацией обратитесь к инструкции для вашего дистрибутива:

* Инструкция для https://wiki.astralinux.ru/pages/viewpage.action?pageId=27362929[Astra Linux]
* Инструкция для https://redos.red-soft.ru/base/redos-7_3/7_3-administation/7_3-domain-redos/7_3-domain-config/7_3-samba-dns-backend-bind9-dlz/7_3-install-samba-dc-bind/?nocache=1728989583495[РЕД ОС]

Особенность конфигурации Samba при использовании с {dv} заключается в том, что необходимо выполнить настройку в файле `smb.conf`. Найдите секцию `[global]` и для параметра `ldap server require strong auth` установите значение `no`, в противном случае подключение не будет установлено. По умолчанию значение параметра `yes`, что требует подключения через SSL/TLS, это вызывает ошибку `The supplied credential is invalid`.
