= Объединение результатов атрибутивного и полнотекстового поиска

При необходимости, результаты атрибутивного и полнотекстового поиска могут быть объединены. Для объединения выполните следующие действия:

. [.ph .cmd]#Настройте поисковые запросы для полнотекстового и атрибутивного поиска.#
. [.ph .cmd]#В окне [.keyword]*Расширенный поиск* перейдите на вкладку [.keyword]*Полнотекстовый*. #
. [.ph .cmd]#В поле [.keyword]*Объединять результаты полнотекстового и атрибутивного поиска* выберите логический оператор *ИЛИ* или *И*, который будет использован при объединении.#
+
Результат объединения будет зависеть от выбранной области поиска.

В частности, если области поиска определена параметром: [.keyword]*Искать в тексте карточек или связанных с ними файлов*:

* в случае объединения по [.keyword .parmname]_И_ будут найдены карточки, удовлетворяющие условиям атрибутивного поиска и содержащие указанную строку в карточке либо в приложенном к ней файле;
* в случае объединения по [.keyword .parmname]_ИЛИ_ будут найдены карточки, которые либо удовлетворяют условиям атрибутивного поиска, либо содержат указанную строку в тексте карточки или файла. Возможные пересечения условий также попадут в результаты поиска.

*На уровень выше:* xref:../topics/SearchConfig.adoc[Настройка поискового запроса]
