= Локализация поисковых запросов

При настройке поисковых запросов можно установить значения параметров, зависящие от языка пользовательского интерфейса. В частности данная возможность поддерживается для названий xref:search-new.adoc[поисковых запросов] и xref:search-new.adoc#group[групп запросов].

WARNING: Функция локализации поисковых запросов по умолчанию отключена.

Чтобы активировать функцию локализации поисковых запросов, администратор {dv} должен включить поддержку локализации значений полей следуя xref:5.5.5@platform:admin:default-localization.adoc[инструкции].

.Чтобы установить значение параметра для определённого языка интерфейса:
. Откройте РМА с языком интерфейса, для которого нужно установить локализованные значения параметров.
+
[NOTE]
====
Например, для запуска РМА с английским интерфейсом откройте в Internet Explorer (Microsoft Edge режиме совместимости с IE) адрес: `\http://Сервер-{dv}/{dv}/?showpanels=32768&langname=enu`.

Дополнительная информация по параметрам запуска РМА xref:5.5.4@winclient:user:launch.adoc#parameters[приведена] в пользовательской документации модуля {wincl}.
====
+
. Создайте новый поисковый запрос или группу запросов, или xref:search-rename.adoc[переименуйте существующий запрос].
. При сохранении поискового запроса укажите название для языка, с которым открыт РМА.
+
В клиенте {dv} для параметров поисковых запросов выбираются их локализованные значения. Если значение для текущего языка интерфейса не установлено, будет использовано значение для языка по умолчанию. Язык локализации по умолчанию xref:5.5.5@platform:admin:default-localization.adoc[устанавливается] администратором {dv}.
