= Локализация поисковых запросов

При настройке поисковых запросов можно установить значения параметров, зависящие от языка пользовательского интерфейса. В частности данная возможность поддерживается для названий xref:CreateNewSearchQuery.adoc[поисковых запросов] и xref:SearchGroup.adoc[групп запросов].

*Функция локализации поисковых запросов по умолчанию отключена.* Для её активации администратор Docsvision должен включить поддержку локализации значений полей следуя инструкции, приведённой в Руководстве администратора модуля «Docsvision 5. Платформа», пункт «Настройка режима локализации полей».

Чтобы установить значение параметра для определённого языка интерфейса:

. Откройте РМА с языком интерфейса, для которого нужно установить локализованные значения параметров.
+
Например, для запуска РМА с английским интерфейсом откройте в Internet Explorer адрес: [.ph .filepath]`http://\{Сервер Docsvision}/docsvision/?showpanels=32768&langname=enu`. Дополнительная информация по параметрам запуску РМА приведена в руководстве пользователя модуля «Docsvision 5. Windows-клиент».
. Создайте новый поисковый запрос или группу запросов, или xref:Search_Rename_Search_Query.adoc[переименуйте существующий запрос].
. При сохранении поискового запроса укажите название для языка, с которым открыт РМА.

При использовании поисковых запросов в клиенте Docsvision для параметров выбираются их локализованные значения. Если значение для текущего языка интерфейса не установлено, будет использовано значение для языка по умолчанию. Язык локализации по умолчанию устанавливается администратором Docsvision (см. Руководстве администратора модуля «Docsvision 5. Платформа», пункт «Настройка режима локализации полей».).

*Parent topic:* xref:../topics/Search_Create_and_Save_Queries_for_AdvancedSearch.adoc[Настройка поисковых запросов]
