= Объединить атрибутивный и полнотекстовый поиск

При необходимости результаты атрибутивного и полнотекстового поиска могут быть объединены.

.Чтобы объединить результаты полнотекстового и атрибутивного поиска:
. Настройте поисковые запросы для полнотекстового и атрибутивного поиска.
. В окне _Расширенный поиск_ перейдите на вкладку _Полнотекстовый_.
. В поле _Объединять результаты полнотекстового и атрибутивного поиска_ выберите логический оператор `ИЛИ` или `И`, который будет использован при объединении.
+
.Результат объединения зависит от выбранной области поиска
****
Например, если области поиска определена параметром *Искать в тексте карточек или связанных с ними файлов*:

* В случае объединения по `И` будут найдены карточки, удовлетворяющие условиям атрибутивного поиска и содержащие указанную строку в карточке либо в приложенном к ней файле.
* В случае объединения по `ИЛИ` будут найдены карточки, которые либо удовлетворяют условиям атрибутивного поиска, либо содержат указанную строку в тексте карточки или файла. Возможные пересечения условий также попадут в результаты поиска.
****
