= Настройка поисковых запросов

Расширенный поиск карточек выполняется на основе поисковых запросов, позволяющих находить все карточки, отвечающие каким-либо определенным критериям, а также по минимальным имеющимся о них сведениям.

Запросы для расширенного поиска карточек, содержащие описание условий поиска, могут использоваться однократно или сохраняться для последующего использования; при этом пользователь может создать виртуальную папку (или несколько виртуальных папок) для хранения результатов расширенного поиска по какому-либо поисковому запросу (запросам). Обновление результатов поиска будет происходить при каждом обращении к виртуальной папке.

Настройка поисковых запросов доступна только администраторам Docsvision и членам группы [.keyword .parmname]_Docsvision Search Query Creators_. Другим пользователям данные запросы доступны через механизм виртуальных папок и в программе «Личный помощник».

* *xref:../topics/CreateNewSearchQuery.adoc[Создание нового поискового запроса]* +
* *xref:../topics/SearchConfig.adoc[Настройка поискового запроса]* +
* *xref:../topics/Search_Loading_and_Change_Query.adoc[Загрузка и изменение поискового запроса из окна 'Расширенный поиск']* +
* *xref:../topics/Search_Assigning_Access_Rights_to_Query.adoc[Назначение прав доступа к запросу]* +
* *xref:../topics/DisableSecurityOnSearch.adoc[Отключение проверки прав доступа для определённого поискового запроса]* +
* *xref:../topics/Search_Rename_Search_Query.adoc[Переименование поискового запроса]* +
* *xref:../topics/Search_Delete_Search_Query.adoc[Удаление поискового запроса]* +
* *xref:../topics/Search_Export_to_Xml.adoc[Экспорт поискового запроса в файл формата .xml]* +
* *xref:../topics/Search_Import_to_Xml.adoc[Импорт поискового запроса из файла формата .xml]* +
* *xref:../topics/SearchLocalization.adoc[Локализация поисковых запросов]* +
* *xref:../topics/DisableSearchRegenFlag.adoc[Признак изменения запроса на уровне БД]* +
