= Настройка представлений

== Общие сведения о настройке представления

Все настройки представлений задаются администратором (или пользователем, обладающим правами редактирования представлений) как комплекс атрибутов, полностью определяющих представление. Пользователь системы может переключаться между разрешенными администратором для папки представлениями, выбирая в меню команды [.ph .menucascade]#[.ph .uicontrol]*Вид* > [.ph .uicontrol]*Текущее представление*#.

Для изменения и редактирования доступны следующие свойства представления:

* количество и состав полей карточки, которые будут отображаться в окне просмотра;
* правила группировки карточек по определенному полю в окне просмотра;
* правила сортировки карточек по определенному параметру;
* фильтр, позволяющий выводить в представлении карточки, выбранные пользователем;
* оформление (цвет, шрифт, линии сетки и т. п.).

Данные представления могут экспортироваться в таблицу Excel, например, при создании отчетов; для этого в настройках каждого представления указывается список доступных для него шаблонов, предназначенных для экспорта данных в Excel и задающих формат итогового документа.

[NOTE]
====
[.note__title]#Внимание:# Шаблоны для экспорта данных в Excel являются общими для всех пользователей и хранятся в базе данных [.dfn .term]_Docsvision_. Вследствие этого при изменении шаблона в файловой системе его следует заново включить в базу данных [.dfn .term]_Docsvision_.
====

== Этапы настройки представления

*Настройка выполняется в программе РМА. Пользователь РМА, выполняющий настройку, должен являться Администратором Docsvision.*

Настройка представлений в общем случае производится в четыре шага:

. Выбор типов карточек, информация о которых будет отображаться в представлении.
. Формирование «шапки» (заголовка) таблицы представления – тех колонок, в которых будут выводиться данные.
. Указание данных, которые будут отображаться в полях представления.
. Настройка внешнего вида представления (задание вариантов группировки и сортировки данных, указание фильтров, цветовых параметров и т.п.).

[NOTE]
====
[.note__title]#Прим.:# Добавить новую колонку в представление и отредактировать данные об уже имеющейся колонке пользователь может на любом этапе настройки представления.
====

* *xref:../topics/SettingView_Creating.adoc[Создание представления]* +
* *xref:../topics/SettingView_Edit_View.adoc[Редактирование представления]* +
* *xref:../topics/SettingView_Order_Settings.adoc[Настройка представлений]* +
* *xref:../topics/SettingView_Setting_Access_Rights.adoc[Права доступа к представлению]* +
* *xref:../topics/SettingView_Delet_View.adoc[Удаление представления]* +
* *xref:../topics/Moving_Views_and_Node.adoc[Перемещение элементов дерева представлений]* +
* *xref:../topics/SettingView_Templates_for_Export_Excel.adoc[Шаблоны для экспорта представления в Excel]* +
* *xref:../topics/ViewExport.adoc[Экспорт представления в файл формата .xml]* +
* *xref:../topics/ViewImport.adoc[Импорт представления из файла формата .xml]* +
* *xref:../topics/ViewLocalization.adoc[Локализация представлений]* +
* *xref:../topics/DisableViewRegenFlag.adoc[Признак изменения представления на уровне БД]* +
