= Дополнительные возможности настройки

От того, какого рода данные должны быть отображены в представлении, зависит сложность его построения. Например, если кроме данных из самой карточки требуется отобразить информацию из связанных карточек (либо из разных разделов одной карточки), то необходимо понимать структуру и принципы присоединения таблиц разделов карточек. Такого рода информацией обладает только администратор Docsvision.

[NOTE]
====
[.note__title]#Внимание:# Получить сведения о структуре карточек можно:

* воспользовавшись утилитой *CardManager* (входит в пакет разработчика) для просмотра структуры полей и секций стандартных карточек;
* воспользовавшись документом *Описание полей стандартных карточек* (входит в пакет разработчика).
====

Для отображения данных, не хранящихся напрямую в карточке, а получаемых по определенному правилу, требуется создать вычисляемое поле (воспользовавшись при этом специальным редактором), что тоже может сделать только администратор Docsvision.

* *xref:../topics/SettingView_Conditions_for_Accession_Section.adoc[Определение условий присоединения раздела]* +
* *xref:../topics/SettingView_Setting_Coloring_Rows.adoc[Настройка выделения строк представления цветом]* +
* *xref:../topics/SettingView_Create_Virtual_Field.adoc[Создание виртуального поля]* +
* *xref:../topics/SettingView_Create_Calculated_Field.adoc[Создание вычисляемого поля]* +
* *xref:../topics/SettingView_Creating_Links_between_Sections.adoc[Определение связей между разделами]* +

*На уровень выше:* xref:../topics/SettingView_Order_Settings.adoc[Настройка представлений]
