= Определение ведущего раздела

Отображаемые поля для каждого типа выбираются из определенного раздела карточки - [.dfn .term]_ведущего_ раздела. Таким образом, [.dfn .term]_ведущий_ в данном представлении раздел - раздел карточки, из которого по умолчанию можно будет выбрать поля для представления. Кроме того, этот раздел будет подставляться по умолчанию при построении связей с другими разделами карточек.

[NOTE]
====
[.note__title]#Note:# Для одного типа карточки в поле *Ведущие разделы карточек* можно указать несколько ведущих разделов (это бывает необходимым при создании сложного представления).

При построении представлений средней сложности в качестве ведущего желательно использовать только один раздел (то есть желательно, чтобы в поле *Ведущие разделы карточек* каждому типу карточки соответствовала только одна строка).
====

Чтобы определить ведущий раздел, выполните следующие действия:

. [.ph .cmd]#Откройте окно xref:SettingView_Selection_Information.html#task_zrd_kjn_g4__view_set_data[[.keyword .wintitle]*Настройка данных представления*].#
. [.ph .cmd]#В поле [.keyword]*Ведущие разделы карточек* выберите раздел:#
* если в представлении предполагается использовать данные карточки, то в качестве ведущего может выступать тот ее раздел, из которого в представлении возможно отобразить больше всего полей;
* если выводящиеся в представлении данные должны быть получены из других карточек (или из других разделов этой же карточки), то ведущим разделом будет выступать тот, по отношению к которому должны быть выстроены связи (определение связей между разделами и карточками доступно только администратору Docsvision).

*Parent topic:* link:../topics/SettingView_Selection_Information.adoc[Настройка данных представления]
