= Настройка представлений

== Общие сведения о настройке представления

Все настройки представлений задаются администратором (или пользователем, обладающим правами редактирования представлений) как комплекс атрибутов, полностью определяющих представление. Пользователь системы может переключаться между разрешенными администратором для папки представлениями, выбирая в меню команды [.ph .menucascade]#*Вид* > *Текущее представление*#.

Для изменения и редактирования доступны следующие свойства представления:

* количество и состав полей карточки, которые будут отображаться в окне просмотра;
* правила группировки карточек по определенному полю в окне просмотра;
* правила сортировки карточек по определенному параметру;
* фильтр, позволяющий выводить в представлении карточки, выбранные пользователем;
* оформление (цвет, шрифт, линии сетки и т. п.).

Данные представления могут экспортироваться в таблицу Excel, например, при создании отчетов; для этого в настройках каждого представления указывается список доступных для него шаблонов, предназначенных для экспорта данных в Excel и задающих формат итогового документа.

[NOTE]
====
[.note__title]#Внимание:# Шаблоны для экспорта данных в Excel являются общими для всех пользователей и хранятся в базе данных _{dv}_. Вследствие этого при изменении шаблона в файловой системе его следует заново включить в базу данных _{dv}_.
====

== Этапы настройки представления

*Настройка выполняется в программе РМА. Пользователь РМА, выполняющий настройку, должен являться Администратором {dv}.*

Настройка представлений в общем случае производится в четыре шага:

. Выбор типов карточек, информация о которых будет отображаться в представлении.
. Формирование "шапки" (заголовка) таблицы представления -- тех колонок, в которых будут выводиться данные.
. Указание данных, которые будут отображаться в полях представления.
. Настройка внешнего вида представления (задание вариантов группировки и сортировки данных, указание фильтров, цветовых параметров и т.п.).

[NOTE]
====
[.note__title]#Прим.:# Добавить новую колонку в представление и отредактировать данные об уже имеющейся колонке пользователь может на любом этапе настройки представления.
====
