= Шаблоны для экспорта представления в Excel

Шаблон Excel – это особый вид рабочей книги, применяемый для создания рабочих книг того же типа в соответствии с указанным в ней образцом. В отличие от обычной книги Excel, имеющей расширение *.xls, файл шаблона имеет расширение *.xlt.

При создании документа на основе шаблона программа Excel автоматически создает его рабочую копию с расширением *.xls, добавляя в конец имени документа порядковый номер. Шаблон-оригинал при этом остается нетронутым и впоследствии может использоваться повторно.

Прежде чем быть указанным в списке доступных шаблонов, файл шаблона должен быть создан с помощью программы Microsoft Excel и сохранен в файловой системе.

* *xref:../topics/SettingView_Creating_New_Template.adoc[Создание нового шаблона для экспорта представления в Excel]* +
* *xref:../topics/SettingView_Access_Rights_to_Template.adoc[Права доступа к шаблону]* +
* *xref:../topics/SettingView_Edit_and_Delet_Template.adoc[Редактирование и удаление шаблона]* +
* *xref:../topics/SettingView_Moving_Template.adoc[Перемещение шаблона в другую папку]* +
* *xref:../topics/SettingView_Placing_Data_when_Exporting_Markers.adoc[Размещение данных при экспорте: маркеры]* +

*На уровень выше:* xref:../topics/SettingView.adoc[Настройка представлений]
