= Журналирование модулей системы через NLog

Журналирование модулей системы выполняется с помощью https://nlog-project.org/[NLog], начиная с {new-log-req}, журнал ведётся в формате JSON.

Обновлённый механизм журналирования требует обновить конфигурационные файлы модулей автоматически или добавить в них новые параметры вручную. Если настройки в конфигурационном файле не указаны, будет действовать не обновлённый, а прежний механизм журналирования.

[#config]
== Настройка параметров журналирования

Параметры журналирования задаются в конфигурационных файлах, расположенных в корневом каталоге каждого модуля. Общая структура конфигурационного файла приведена ниже, однако модули могут иметь особенности настройки журналирования. Рекомендуется свериться с разделом журналирования для каждого отдельного модуля.

.Генерализованный пример конфигурационного файла:
[source,json]
----
{
  "NLog": {
    "throwConfigExceptions": false, <.>
    "extensions": [ <.>
    { "assembly": "DocsVision.Something" },
    { "assembly": "NLog.Extensions.Logging" },
    { "assembly": "NLog.Web.AspNetCore" }
    ],
    "variables": { <.>
      "fileLogLevel": "Error", <.>
      "consoleLogLevel": "Error", <.>
      "enableFileLogging": "true", <.>
      "enableConsoleLogging": "true", <.>
      "jsonLayout": { <.>
        "type": "JsonLayout", <.>
        "includeAllProperties": true, <.>
        "attributes": [ <.>
          {
          "name": "timestamp", <.>
          "layout": "${date:format=yyyy-MM-dd HH\\:mm\\:ss.fff}" <.>
          }
        ]
      }
    },
    "targets": { <.>
      "async": true, <.>
      "logFile": { <.>
        "type": "File", <.>
        "fileName": "${gdc:baseLogFolder}/docsvision/MODULE/MODULE${event-properties:item=Tenant} PID ${processId} ${shortdate}.log", <.>
        "layout": "[${longdate}][${level}][${callsite}] ${message} ${exception:format=tostring,Data}", <.>
        "archiveEvery": "Day", <.>
        "archiveAboveSize": 314572800, <.>
        "archiveFileName": "${gdc:baseLogFolder}/${gdc:moduleName}/archives/${gdc:moduleName} {#}.log", <.>
        "archiveNumbering": "DateAndSequence", <.>
        "archiveDateFormat": "yyyy-MM-dd", <.>
        "maxArchiveFiles": 30, <.>
        "createDirs": true <.>
      },
      "logConsole": { <.>
        "type": "Console",
        "layout": "${var:jsonLayout}"
      }
    },
    "rules": [ <.>
      {
      "logger": "*",
      "minLevel": "Warn",
      "writeTo": "logFile"
      }
    ]
  }
}
----
<.> `throwConfigExceptions` -- определяет поведение приложения при обнаружении ошибок в конфигурации NLog.
+
Если параметр установлен в `true`, любая ошибка в конфигурации вызовет исключение.
+
<.> `extensions` -- загружает дополнительные сборки (`.dll`), расширяющие возможности NLog.
<.> `variables` -- раздел определяет параметры, которые используются в других частях конфигурации.
<.> `fileLogLevel` -- задаёт уровень журналирования для файла журнала.
<.> `consoleLogLevel` -- задаёт уровень журналирования для консоли (stdout/stderr).
<.> `enableFileLogging` -- включает или отключает ведение журнала в файл.
<.> `enableConsoleLogging` -- включает или отключает ведение журнала в консоль (stdout/stderr).
<.> `jsonLayout` -- определяет JSON-структуру сообщений журнала.
<.> `type` -- указывает на использование JSON-макета.
<.> `includeAllProperties` -- регулирует, будут ли добавляться в вывод все дополнительные свойства, переданные в контексте журналирования.
<.> `attributes` -- раздел с парными параметрами вида `"name"`/`"layout"`, определяющий поля JSON.
<.> `name` -- значение `timestamp` добавляет отметку времени.
<.> `layout` -- значение `${date:format=yyyy-MM-dd HH\\:mm\\:ss.fff}` задаёт формат отображения времени.
<.> `targets` -- настройки режимов журналирования.
<.> `async` -- регулирует асинхронную обработку целей, указанных в этом блоке. Журналирование выполняется в фоновом режиме, не блокируя работу системы, что повышает производительность при высокой нагрузке.
<.> `logFile` -- настройки для режима вывода журнала в файл.
<.> `type` -- указывает на использование файла.
<.> `fileName` -- формирует шаблон имени файла, в параметре можно использовать https://github.com/nlog/NLog/wiki/File-target[допустимые для NLog переменные].
<.> `layout` -- ссылка на общий JSON-формат, определённый в `jsonLayout`.
<.> `archiveEvery` -- создавать новый архивный файл каждый заданный период, по умолчанию -- каждый день.
<.> `archiveAboveSize` -- если текущий файл превышает `300` Мб (значение по умолчанию), он будет немедленно архивирован, даже если заданный в `archiveEvery` период не завершился.
<.> `archiveFileName` -- шаблон имени для архивов, `&#123;#&#125;` заменяется на номер архива.
<.> `archiveNumbering` -- значение `DateAndSequence` задаёт нумерацию архивов по дате и порядковому номеру (например, `MyLog 2026-09-09 1.log`).
<.> `archiveDateFormat` -- задаёт формат даты, которая подставляется в имя архивного файла при архивации журнала.
<.> `maxArchiveFiles` -- максимальное количество архивных файлов, после которого старые файлы будут удаляться. По умолчанию -- `30`.
<.> `createDirs` -- флаг регулирует автоматическое создание каталогов журналов. Каталоги будут создаваться автоматически, когда флаг в значении `true`.
<.> `logConsole` -- настройки для режима вывода журнала в stdout/stderr процесса, например _journald_ в терминале Linux. Формат -- тот же JSON, что и для файла.
<.> `rules` -- правила журналирования. Определяют, какой логгер (`logger`), с каким уровнем (`minLevel`, `maxLevel`) и в каком режиме (`writeTo`) будет писать сообщения.
+
Допустимые уровни протоколирования приведены https://github.com/nlog/NLog/wiki/Configuration-file#log-levels[на странице NLog в GitHub]. +
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.

[#log-modes]
== Режимы журналирования

Журналирование через NLog поддерживает два режима, каждый из которых может быть настроен независимо друг от друга или одновременно.

[cols=",", options="header"]
|===
|Режим |Параметр конфигурации
|Файл |`logFile`
|Консоль (stdout/stderr) |`logConsole`
|===

Оба режима ведут журнал в одинаковом JSON-формате и могут быть задействованы одновременно в Windows или Linux.
// Но не в Docker

[#archivation]
== Архивирование журналов работы

Для журналов, создаваемых с NLog, задействована архивация. Поведение по умолчанию -- архивировать журнал за предыдущий день. Если текущий размер журнала превышает 300 Мб, он будет архивирован автоматически, даже если заданный период не завершился.

По умолчанию если количество архивных файлов превышает 30, самые старые файлы будут удаляться.

Архивированием файлов журналов управляют следующие параметры NLog (пример конфигурационного файла см. <<config,выше>>):

* `archiveEvery` -- создавать новый архивный файл каждый заданный период, в данном случае -- день.
* `archiveAboveSize` -- если текущий файл превышает `300` Мб (значение по умолчанию), он будет немедленно архивирован, даже если заданный в `archiveEvery` период не завершился.
* `archiveFileName` -- шаблон имени для архивов, `&#123;#&#125;` заменяется на номер архива.
* `archiveNumbering` -- значение `DateAndSequence` задаёт нумерацию архивов по дате и порядковому номеру (например, `MyLog 2026-09-09 1.log`).
* `archiveDateFormat` -- задаёт формат даты, которая подставляется в имя архивного файла при архивации журнала.
* `maxArchiveFiles` -- максимальное количество архивных файлов, после которого старые файлы будут удаляться. По умолчанию -- `30`.
* `createDirs` -- флаг регулирует автоматическое создание каталогов журналов. Каталоги будут создаваться автоматически, когда флаг в значении `true`.

[#env-vars]
== Переменные среды для журнала NLog

Параметры журналирования NLog могут быть переопределены через переменные окружения.

Переменные окружения службы преобладают над переменными окружения машины, которые преобладают над параметрами в конфигурационных файлах. После получения первого значения последующие не проверяются.

Переменные окружения указываются по аналогии с параметрами в конфигурационных файлах `appsettings.json`, вложенность параметров указывается через двойное подчёркивание: `&#95;&#95;`.

Например, переменная окружения `NLog&#95;&#95;variables&#95;&#95;fileLogLevel` эквивалентна указанию параметра
menu:NLog[variables > fileLogLevel] в конфигурационном файле.

Аналогичным образом можно задать все остальные параметры, например:

[source]
----
NLog__variables__fileLogLevel=Trace
NLog__variables__consoleLogLevel=Info
NLog__variables__enableFileLogging=false
NLog__variables__enableConsoleLogging=true
----

[#archive]
== Архивация журналов работы

300 МБ, 30 файлов, DateAndSequence

[#read-logs]
== Работа с журналом в формате JSON

Обновлённый жунрал NLog пишется в JSON одной строкой, поэтому обычная команда вида:

 sudo journalctl -u dvappserver

Выводит плохо читаемую человеком строку формата JSON:

[source,json]
----
{"timestamp":"2026-08-10 17:53:23.755","level":"INFO","module":"StorageServerRuntime","message":"Trying load session..."}
----

Для удобства чтения человеком можно воспользловаться утилитой _jq_, которая выдаст более читаемый вид:

[source,json]
----
{
"timestamp": "2026-08-10 17:53:23.755",
"level": "INFO",
"module": "StorageServerRuntime",
"message": "Trying load session..."
}
----

. Установить _jq_ можно следующими командами:
+
[tabs]
====
{os1}::
+
[source,bash]
----
sudo apt-get update
sudo apt-get install jq
----

{os2}::
+
[source,bash]
----
sudo dnf makecache
sudo dnf install jq
----
====
+
. Прочитать журнал полностью можно следующим образом:
+
 $ sudo journalctl -u dvappserver -o cat | jq .
+
Команда обработает весь доступный журнал. Если журнал большой, лучше открыть его через _less_:
+
 $ sudo journalctl -u dvappserver -o cat | jq -C . | less -R
+
Навигация по журналу выполняется при помощи клавиш на клавиатуре: kbd:[→], kbd:[←], kbd:[PageUp], kbd:[PageDown], выполнять поиск нажатием kbd:[/], выйти из просмотра журнала клавишей kbd:[q].
+
. Если в журнале сохранились записи от прежнего текстового журнала, не в формате JSON, _jq_ выдаст ошибку обработки.
+
В таком случае можно либо одновременно смотреть журналы в обоих форматах, либо удалить старые журналы, оставив только новые в формате JSON:
+
[tabs]
====
Смотреть оба формата::
+
Выполните команду:
+
[source,bash]
----
sudo journalctl -u dvappserver -o cat | jq -C -Rr 'fromjson? // .' | less -R
----

Оставить только JSON::
+
Выполните команды:
+
[WARNING]
=====
После выполнения команд будут удалены текстовые журналы всей системы. Восстановить их будет невозможно.
=====
+
[source,bash]
----
sudo journalctl --rotate
sudo journalctl --vacuum-time=1s
----
====

[#commands]
=== Полезные команды для работы с журналированием NLog

.Смотреть журнал полностью с навигацией:
 $ sudo journalctl -u dvappserver -o cat | jq -C . | less -R

.Смотреть последние 1000 записей:
 $ sudo journalctl -u dvappserver -n 1000 -o cat | jq -C . | less -R

.Просматривать журнал в реальном времени:
 $ sudo journalctl -u dvappserver -n 0 -f -o cat | jq --unbuffered .

.Смотреть журналы за последний час:
 $ sudo journalctl -u dvappserver --since "1 hour ago" -o cat | jq -C . | less -R

.Смотреть журнал с конкретной даты/времени:
 $ sudo journalctl -u dvappserver --since "2026-08-10 17:00:00" -o cat | jq -C . | less -R

.Смотреть одновременно журнал в текстовом и JSON формате:
 $ sudo journalctl -u dvappserver -o cat | jq -C -Rr 'fromjson? // .' | less -R

.Смотреть только сообщения уровня "ОШИБКА":
 $ sudo journalctl -u dvappserver -o cat | jq 'select(.level == "ERROR")'

[#modules]
== Разделы документации модулей

Ниже дан список страниц документации для модулей, на которых приведена документация о журналировании с помощью NLog. Рекомендуется ознакомиться с приведённой информацией, чтобы узнать особенности журналирования для каждого модуля:

* "xref:settings-service:admin:log.adoc[]".
* "xref:platform:console:file-service-logging.adoc[Журнал работы файлового сервиса]"

