= Настройка представлений

== Общие сведения о настройке представления

Все настройки представлений задаются администратором или пользователем, обладающим правами редактирования представлений/ Настройки представлений являются комплексом атрибутов, полностью определяющих представление.

Пользователь системы может переключаться между разрешёнными администратором для папки представлениями, выбирая в меню команды menu:Вид[Текущее представление].

.Следующие свойства представления доступны для изменения:
* Количество и состав полей карточки, которые будут отображаться в окне просмотра.
* Правила группировки карточек по определённому полю в окне просмотра.
* Правила сортировки карточек по определённому параметру.
* Фильтр, позволяющий выводить в представлении карточки, выбранные пользователем.
* Оформление (цвет, шрифт, линии сетки и т. п.).

Данные представления могут быть экспортированы в таблицу Excel, например, при создании отчётов. Для этого в настройках каждого представления указывается список доступных для него шаблонов, предназначенных для экспорта данных в Excel и задающих формат итогового документа.

[WARNING]
====
Шаблоны для экспорта данных в Excel являются общими для всех пользователей и хранятся в базе данных {dv}. Поэтому при изменении шаблона в файловой системе, его следует заново включить в базу данных {dv}.
====

== Этапы настройки представления

NOTE: Настройка выполняется в программе РМА. Пользователь РМА, выполняющий настройку, должен являться Администратором {dv}.

.Настройка представлений в общем случае производится в четыре шага:
. Выбор типов карточек, информация о которых будет отображаться в представлении.
. Формирование "шапки" (заголовка) таблицы представления -- тех колонок, в которых будут выводиться данные.
. Указание данных, которые будут отображаться в полях представления.
. Настройка внешнего вида представления (задание вариантов группировки и сортировки данных, указание фильтров, цветовых параметров и т.п.).

[NOTE]
====
Добавить новую колонку в представление и отредактировать данные об уже имеющейся колонке пользователь может на любом этапе настройки представления.
====
