= Локализация представлений

При настройке представления {dv} можно установить значения параметров, зависящие от языка пользовательского интерфейса. В частности данная возможность поддерживается для следующих параметров:

* названия xref:view-create.adoc#view[представлений] и xref:view-create.adoc#group[групп представлений],
* названия xref:SettingView_Settings_ColumnProperties.adoc[колонок представлений],
* названия строк агрегации данных, используемые в xref:SettingView_Grouping_Data_View.adoc[группировке данных].

*Функция локализации представлений по умолчанию отключена.* Для её активации администратор {dv} должен включить поддержку локализации значений полей следуя инструкции, приведённой в Руководстве администратора модуля "{dv} 5. Платформа", пункт "Настройка режима локализации полей".

Чтобы установить значение параметра для определённого языка интерфейса:

. Откройте РМА с языком интерфейса, для которого нужно установить локализованные значения параметров.
+
Например, для запуска РМА с английским интерфейсом откройте в Internet Explorer адрес: `http://\{Сервер {dv}}/{dv}/?showpanels=32768&langname=enu`. Дополнительная информация по параметрам запуску РМА приведена в руководстве пользователя модуля "{dv} 5. {wincl}".
. Перейдите к настройке параметра представления, который нужно локализовать. Например, создайте новое представления.
. Установите значение параметра для языка, с которым открыт РМА.
. Сохраните настройки разметки.

При использовании представления в клиенте {dv} для параметров выбираются их локализованные значения. Если значение для текущего языка интерфейса не установлено, будет использовано значение для языка по умолчанию. Язык локализации по умолчанию устанавливается администратором {dv} (см. Руководстве администратора модуля "{dv} 5. Платформа", пункт "Настройка режима локализации полей".).

image: