= Локализация представлений

При настройке представления Docsvision можно установить значения параметров, зависящие от языка пользовательского интерфейса. В частности данная возможность поддерживается для следующих параметров:

* названия xref:SettingView_Creating_New_View.adoc[представлений] и xref:SettingView_Creating_New_Node.adoc[групп представлений],
* названия xref:SettingView_Settings_ColumnProperties.adoc[колонок представлений],
* названия строк агрегации данных, используемые в xref:SettingView_Grouping_Data_View.adoc[группировке данных].

*Функция локализации представлений по умолчанию отключена.* Для её активации администратор Docsvision должен включить поддержку локализации значений полей следуя инструкции, приведённой в Руководстве администратора модуля «Docsvision 5. Платформа», пункт «Настройка режима локализации полей».

Чтобы установить значение параметра для определённого языка интерфейса:

. Откройте РМА с языком интерфейса, для которого нужно установить локализованные значения параметров.
+
Например, для запуска РМА с английским интерфейсом откройте в Internet Explorer адрес: [.ph .filepath]`http://\{Сервер Docsvision}/docsvision/?showpanels=32768&langname=enu`. Дополнительная информация по параметрам запуску РМА приведена в руководстве пользователя модуля «Docsvision 5. Windows-клиент».
. Перейдите к настройке параметра представления, который нужно локализовать. Например, создайте новое представления.
. Установите значение параметра для языка, с которым открыт РМА.
. Сохраните настройки разметки.

При использовании представления в клиенте Docsvision для параметров выбираются их локализованные значения. Если значение для текущего языка интерфейса не установлено, будет использовано значение для языка по умолчанию. Язык локализации по умолчанию устанавливается администратором Docsvision (см. Руководстве администратора модуля «Docsvision 5. Платформа», пункт «Настройка режима локализации полей».).

*Parent topic:* xref:../topics/SettingView.adoc[Настройка представлений]
