= Локализация представлений

При настройке представления {dv} можно установить значения параметров, зависящие от языка пользовательского интерфейса.

.В частности данная возможность поддерживается для следующих параметров:
* Названия xref:view-create.adoc#view[представлений] и xref:view-create.adoc#group[групп представлений].
* Названия xref:view-settings-colums.adoc#propeties[колонок представлений].
* Названия строк агрегации данных, используемые в xref:view-group.adoc[группировке данных].

IMPORTANT: Функция локализации представлений по умолчанию отключена.

Чтобы включить функцию локализации представлений, администратор {dv} должен включить поддержку локализации значений полей следуя инструкции, приведённой в пункте xref:platform:admin:default-localization.adoc["Настройка режима локализации полей"] руководства по администрированию модуля {pl}.

.Чтобы установить значение параметра для определённого языка интерфейса:
. Откройте РМА с языком интерфейса, для которого нужно установить локализованные значения параметров.
+
[TIP]
====
Например, для запуска РМА с английским интерфейсом откройте в Internet Explorer адрес: `\http://Сервер-{dv}/{dv}/?showpanels=32768&langname=enu`.

Дополнительная информация по параметрам запуска РМА xref:winclient:user:launch.adoc#parameters[приведена] в руководстве пользователя модуля {wincl}.
====
+
. Настройте параметр представления, который нужно локализовать. Например, создайте новое представления.
. Установите значение параметра для языка, с которым открыт РМА.
. Сохраните настройки разметки.
+
При использовании представления в клиенте {dv} для параметров выбираются их локализованные значения. Если значение для текущего языка интерфейса не установлено, будет использовано значение для языка по умолчанию.
+
Язык локализации по умолчанию устанавливается администратором {dv} (см. пункт xref:platform:admin:default-localization.adoc["Настройка режима локализации полей"]).
