= Определить ведущий раздел

Отображаемые поля для каждого типа выбираются из определенного раздела карточки -- _ведущего_ раздела. Таким образом, _ведущий_ в данном представлении раздел -- раздел карточки, из которого по умолчанию можно будет выбрать поля для представления. Кроме того, этот раздел будет подставляться по умолчанию при построении связей с другими разделами карточек.

[NOTE]
====
Для одного типа карточки в поле _Ведущие разделы карточек_ можно указать несколько ведущих разделов (это бывает необходимым при создании сложного представления).

При построении представлений средней сложности в качестве ведущего желательно использовать только один раздел, то есть желательно, чтобы в поле _Ведущие разделы карточек_ каждому типу карточки соответствовала только одна строка.
====

.Чтобы определить ведущий раздел:
. Откройте окно xref:view-data-settings.adoc#settings-window["Настройка данных представления"].
. В поле _Ведущие разделы карточек_ выберите раздел:
* Если в представлении предполагается использовать данные карточки, то в качестве ведущего может выступать тот ее раздел, из которого в представлении возможно отобразить больше всего полей.
* Если выводящиеся в представлении данные должны быть получены из других карточек (или из других разделов этой же карточки), то ведущим разделом будет выступать тот, по отношению к которому должны быть выстроены связи (определение связей между разделами и карточками доступно только администратору {dv}).
