[#modes]
== Режимы журналирования

Система поддерживает два режима журналирования, каждый режим может быть настроен независимо друг от друга или одновременно.

[cols=",,", options="header"]
|===
|Режим |Параметр конфигурации |Переключатель
|Файл |`logFile` |`enableFileLogging`
|Консоль (stdout/stderr) |`logConsole`  |`enableConsoleLogging`
|===

Оба режима ведут журнал в одинаковом JSON-формате и могут быть задействованы одновременно в Windows или Linux.
// Но не в Docker

[#archivation]
== Архивирование журналов работы

По умолчанию файлы журналов архивируются каждый день или сразу, когда файл журнала достигает 300 Мб. Архивные файлы журнала старше 30 дней удаляются.

Подробнее про архивирование см. в документации по настройке системы "xref:GBL-3610@engineer:ROOT:system-logging.adoc#archivation[Архивирование журналов работы]".

[#redefine]
== Переопределение параметров

Параметры журналирования могут быть переопределены через переменные окружения. Параметры, заданные через переменные окружения преобладают над значениями, указанными в конфигурационном файле.

TIP: Подробнее про переопределение параметров с использованием переменных окружения см. в руководстве по настройке, раздел "xref:GBL-3610@engineer:ROOT:system-logging.adoc#env-vars[Переменные среды для журнала NLog]".
